import { 
  Activity, 
  Apple,
  BarChart3,
  Calendar,
  Check,
  ChevronDown,
  ChevronRight,
  Clock,
  X,
  Compass,
  Crown,
  Dumbbell,
  Flame,
  Flag,
  Zap,
  Grid3x3,
  Heart,
  Lightbulb,
  List,
  Menu,
  Moon,
  Pause,
  Pill,
  Play,
  Plus,
  RefreshCw,
  RotateCcw,
  Search,
  Settings,
  Shield,
  Star,
  Sun,
  Sunrise,
  Target,
  Timer,
  TrendingUp,
  Trophy,
  Utensils,
  Video,
  Filter,
  AlertTriangle,
  Info,
  ArrowLeft,
  Droplets,
  TrendingUp as Analytics,
  GripHorizontal,
  User,
  Download,
  Printer,
  Minus
} from 'lucide-react';

export const Icons = {
  activity: Activity,
  analytics: Analytics,
  apple: Apple,
  barChart: BarChart3,
  calendar: Calendar,
  check: Check,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  clock: Clock,
  close: X,
  compass: Compass,
  crown: Crown,
  dumbbell: Dumbbell,
  fire: Flame,
  flag: Flag,
  flame: Zap,
  grid: Grid3x3,
  heart: Heart,
  lightbulb: Lightbulb,
  list: List,
  menu: Menu,
  moon: Moon,
  pause: Pause,
  pill: Pill,
  play: Play,
  plus: Plus,
  refreshCw: RefreshCw,
  reset: RotateCcw,
  search: Search,
  settings: Settings,
  shield: Shield,
  star: Star,
  sun: Sun,
  sunrise: Sunrise,
  target: Target,
  timer: Timer,
  trendingUp: TrendingUp,
  trophy: Trophy,
  utensils: Utensils,
  video: Video,
  filter: Filter,
  alertTriangle: AlertTriangle,
  info: Info,
  arrowLeft: ArrowLeft,
  droplets: Droplets,
  grip: GripHorizontal,
  user: User,
  download: Download,
  printer: Printer,
  minus: Minus,
} as const;

export type IconName = keyof typeof Icons;