import { 
  Search, 
  Heart, 
  Menu, 
  Sun, 
  Moon, 
  Play, 
  Pause, 
  RotateCcw, 
  Check, 
  BarChart3, 
  Settings, 
  Printer, 
  X,
  Plus,
  Minus,
  Video,
  Target,
  ArrowLeft,
  Lightbulb,
  Timer,
  Activity,
  TrendingUp,
  User,
  Calendar,
  Clock,
  ChevronRight,
  Filter,
  Star
} from 'lucide-react';

export const Icons = {
  search: Search,
  heart: Heart,
  menu: Menu,
  sun: Sun,
  moon: Moon,
  play: Play,
  pause: Pause,
  reset: RotateCcw,
  check: Check,
  analytics: BarChart3,
  settings: Settings,
  printer: Printer,
  close: X,
  plus: Plus,
  minus: Minus,
  video: Video,
  target: Target,
  back: ArrowLeft,
  tip: Lightbulb,
  timer: Timer,
  activity: Activity,
  trending: TrendingUp,
  user: User,
  calendar: Calendar,
  clock: Clock,
  chevronRight: ChevronRight,
  filter: Filter,
  star: Star
} as const;

export type IconName = keyof typeof Icons;